# Generated by Django 5.2.5 on 2025-08-14 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='name',
        ),
        migrations.AddField(
            model_name='feature',
            name='title',
            field=models.CharField(default='Hello Python, Django, NextJs, My First Fullstack Project', max_length=200),
        ),
        migrations.AlterField(
            model_name='feature',
            name='description',
            field=models.TextField(),
        ),
    ]
